//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fermentation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fermentation()
        {
            this.StorageWine = new HashSet<StorageWine>();
        }
    
        public int IDFermentation { get; set; }
        public int IDYield { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public decimal Temperature { get; set; }
        public decimal LevelSugar { get; set; }
        public string Description { get; set; }
        public int IDGrowingConditions { get; set; }
        public Nullable<int> Count { get; set; }
        public string Measure { get; set; }
    
        public virtual Yield Yield { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StorageWine> StorageWine { get; set; }
        public virtual GrowingConditions GrowingConditions { get; set; }
    }
}
