//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fermentation
    {
        public int IDFermentation { get; set; }
        public int IDYield { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public decimal Temperature { get; set; }
        public decimal LevelSugar { get; set; }
        public int IDParty { get; set; }
        public string Description { get; set; }
        public int IDGrowingConditions { get; set; }
    
        public virtual Yield Yield { get; set; }
        public virtual Party Party { get; set; }
        public virtual GrowingConditions GrowingConditions { get; set; }
    }
}
