//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int IDOrders { get; set; }
        public int IDClient { get; set; }
        public int IDProduct { get; set; }
        public int IDEmployee { get; set; }
        public int Count { get; set; }
        public System.DateTime DateOrder { get; set; }
        public decimal Sum { get; set; }
        public int IDPayment { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Products Products { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual PaymentsOrder PaymentsOrder { get; set; }
    }
}
