//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentsOrder
    {
        public int IDOrders { get; set; }
        public decimal Sum { get; set; }
        public System.DateTime DatePayments { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
