//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageWine
    {
        public int IDStorageWine { get; set; }
        public int IDFermentation { get; set; }
        public int IDStorage { get; set; }
        public string IDGrowingConditions { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public int IDParty { get; set; }
    
        public virtual Party Party { get; set; }
    }
}
